import { ThemePreset } from "../types";
import { eightBitPreset } from "./8-bit";

export const defaultPresets: Record<string, ThemePreset> = {
  // ──────────────────────────────────────────────────────────────────────────
  // 8-Bit — Neo-Retro Cyberpunk Pixel Art
  // ──────────────────────────────────────────────────────────────────────────
  "8-bit": eightBitPreset,
  // ──────────────────────────────────────────────────────────────────────────
  // Modern Minimal — clean blue-accented UI
  // ──────────────────────────────────────────────────────────────────────────
  "modern-minimal": {
    label: "Modern Minimal",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#333333",
        card: "#ffffff",
        "card-foreground": "#333333",
        popover: "#ffffff",
        "popover-foreground": "#333333",
        primary: "#3b82f6",
        "primary-foreground": "#ffffff",
        secondary: "#f3f4f6",
        "secondary-foreground": "#4b5563",
        muted: "#f9fafb",
        "muted-foreground": "#6b7280",
        accent: "#e0f2fe",
        "accent-foreground": "#1e3a8a",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#e5e7eb",
        input: "#e5e7eb",
        ring: "#3b82f6",
        "chart-1": "#3b82f6",
        "chart-2": "#2563eb",
        "chart-3": "#1d4ed8",
        "chart-4": "#1e40af",
        "chart-5": "#1e3a8a",
        radius: "0.375rem",
        sidebar: "#f9fafb",
        "sidebar-foreground": "#333333",
        "sidebar-primary": "#3b82f6",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e0f2fe",
        "sidebar-accent-foreground": "#1e3a8a",
        "sidebar-border": "#e5e7eb",
        "sidebar-ring": "#3b82f6",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Source Serif 4, serif",
        "font-mono": "JetBrains Mono, monospace",
      },
      dark: {
        background: "#171717",
        foreground: "#e5e5e5",
        card: "#262626",
        "card-foreground": "#e5e5e5",
        popover: "#262626",
        "popover-foreground": "#e5e5e5",
        primary: "#3b82f6",
        "primary-foreground": "#ffffff",
        secondary: "#262626",
        "secondary-foreground": "#e5e5e5",
        muted: "#1f1f1f",
        "muted-foreground": "#a3a3a3",
        accent: "#1e3a8a",
        "accent-foreground": "#bfdbfe",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#404040",
        input: "#404040",
        ring: "#3b82f6",
        "chart-1": "#60a5fa",
        "chart-2": "#3b82f6",
        "chart-3": "#2563eb",
        "chart-4": "#1d4ed8",
        "chart-5": "#1e40af",
        radius: "0.375rem",
        sidebar: "#171717",
        "sidebar-foreground": "#e5e5e5",
        "sidebar-primary": "#3b82f6",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#1e3a8a",
        "sidebar-accent-foreground": "#bfdbfe",
        "sidebar-border": "#404040",
        "sidebar-ring": "#3b82f6",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Violet Bloom — vibrant purple creative feel
  // ──────────────────────────────────────────────────────────────────────────
  "violet-bloom": {
    label: "Violet Bloom",
    styles: {
      light: {
        background: "#fdfdfd",
        foreground: "#000000",
        card: "#fdfdfd",
        "card-foreground": "#000000",
        popover: "#fcfcfc",
        "popover-foreground": "#000000",
        primary: "#7033ff",
        "primary-foreground": "#ffffff",
        secondary: "#edf0f4",
        "secondary-foreground": "#080808",
        muted: "#f5f5f5",
        "muted-foreground": "#525252",
        accent: "#e2ebff",
        "accent-foreground": "#1e69dc",
        destructive: "#e54b4f",
        "destructive-foreground": "#ffffff",
        border: "#e7e7ee",
        input: "#ebebeb",
        ring: "#000000",
        "chart-1": "#4ac885",
        "chart-2": "#7033ff",
        "chart-3": "#fd822b",
        "chart-4": "#3276e4",
        "chart-5": "#747474",
        sidebar: "#f5f8fb",
        "sidebar-foreground": "#000000",
        "sidebar-primary": "#000000",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#ebebeb",
        "sidebar-accent-foreground": "#000000",
        "sidebar-border": "#ebebeb",
        "sidebar-ring": "#000000",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(0 0% 0%)",
        "shadow-opacity": "0.16",
        "shadow-blur": "3px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },
      dark: {
        background: "#1a1b1e",
        foreground: "#f0f0f0",
        card: "#222327",
        "card-foreground": "#f0f0f0",
        popover: "#222327",
        "popover-foreground": "#f0f0f0",
        primary: "#8c5cff",
        "primary-foreground": "#ffffff",
        secondary: "#2a2c33",
        "secondary-foreground": "#f0f0f0",
        muted: "#2a2c33",
        "muted-foreground": "#a0a0a0",
        accent: "#1e293b",
        "accent-foreground": "#79c0ff",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#33353a",
        input: "#33353a",
        ring: "#8c5cff",
        "chart-1": "#4ade80",
        "chart-2": "#8c5cff",
        "chart-3": "#fca5a5",
        "chart-4": "#5993f4",
        "chart-5": "#a0a0a0",
        sidebar: "#161618",
        "sidebar-foreground": "#f0f0f0",
        "sidebar-primary": "#8c5cff",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#2a2c33",
        "sidebar-accent-foreground": "#8c5cff",
        "sidebar-border": "#33353a",
        "sidebar-ring": "#8c5cff",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Dark Neutral — monochrome sophistication
  // ──────────────────────────────────────────────────────────────────────────
  "dark-neutral": {
    label: "Dark Neutral",
    styles: {
      light: {
        background: "#fafafa",
        foreground: "#18181b",
        card: "#ffffff",
        "card-foreground": "#18181b",
        popover: "#ffffff",
        "popover-foreground": "#18181b",
        primary: "#18181b",
        "primary-foreground": "#fafafa",
        secondary: "#f4f4f5",
        "secondary-foreground": "#18181b",
        muted: "#f4f4f5",
        "muted-foreground": "#71717a",
        accent: "#f4f4f5",
        "accent-foreground": "#18181b",
        destructive: "#ef4444",
        "destructive-foreground": "#fafafa",
        border: "#e4e4e7",
        input: "#e4e4e7",
        ring: "#a1a1aa",
        "chart-1": "#18181b",
        "chart-2": "#52525b",
        "chart-3": "#a1a1aa",
        "chart-4": "#d4d4d8",
        "chart-5": "#fafafa",
        sidebar: "#fafafa",
        "sidebar-foreground": "#18181b",
        "sidebar-primary": "#18181b",
        "sidebar-primary-foreground": "#fafafa",
        "sidebar-accent": "#f4f4f5",
        "sidebar-accent-foreground": "#18181b",
        "sidebar-border": "#e4e4e7",
        "sidebar-ring": "#a1a1aa",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#09090b",
        foreground: "#fafafa",
        card: "#09090b",
        "card-foreground": "#fafafa",
        popover: "#09090b",
        "popover-foreground": "#fafafa",
        primary: "#fafafa",
        "primary-foreground": "#18181b",
        secondary: "#27272a",
        "secondary-foreground": "#fafafa",
        muted: "#27272a",
        "muted-foreground": "#a1a1aa",
        accent: "#27272a",
        "accent-foreground": "#fafafa",
        destructive: "#7f1d1d",
        "destructive-foreground": "#fafafa",
        border: "#27272a",
        input: "#27272a",
        ring: "#d4d4d8",
        "chart-1": "#fafafa",
        "chart-2": "#a1a1aa",
        "chart-3": "#52525b",
        "chart-4": "#27272a",
        "chart-5": "#18181b",
        sidebar: "#09090b",
        "sidebar-foreground": "#fafafa",
        "sidebar-primary": "#fafafa",
        "sidebar-primary-foreground": "#18181b",
        "sidebar-accent": "#27272a",
        "sidebar-accent-foreground": "#fafafa",
        "sidebar-border": "#27272a",
        "sidebar-ring": "#d4d4d8",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Rose Pine — warm muted pastels on dark plum backgrounds
  // ──────────────────────────────────────────────────────────────────────────
  "rose-pine": {
    label: "Rosé Pine",
    styles: {
      light: {
        background: "#faf4ed",
        foreground: "#575279",
        card: "#fffaf3",
        "card-foreground": "#575279",
        popover: "#fffaf3",
        "popover-foreground": "#575279",
        primary: "#d7827e",
        "primary-foreground": "#fffaf3",
        secondary: "#f2e9de",
        "secondary-foreground": "#575279",
        muted: "#f2e9de",
        "muted-foreground": "#9893a5",
        accent: "#eee0cf",
        "accent-foreground": "#575279",
        destructive: "#b4637a",
        "destructive-foreground": "#fffaf3",
        border: "#dfdad9",
        input: "#dfdad9",
        ring: "#d7827e",
        "chart-1": "#d7827e",
        "chart-2": "#ea9d34",
        "chart-3": "#56949f",
        "chart-4": "#907aa9",
        "chart-5": "#286983",
        radius: "0.75rem",
        sidebar: "#f2e9de",
        "sidebar-foreground": "#575279",
        "sidebar-primary": "#d7827e",
        "sidebar-primary-foreground": "#fffaf3",
        "sidebar-accent": "#eee0cf",
        "sidebar-accent-foreground": "#575279",
        "sidebar-border": "#dfdad9",
        "sidebar-ring": "#d7827e",
        "font-sans": "Nunito, sans-serif",
        "font-serif": "Libre Baskerville, serif",
        "font-mono": "Fira Code, monospace",
        "shadow-opacity": "0.06",
        "shadow-blur": "8px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
        "letter-spacing": "-0.01em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#191724",
        foreground: "#e0def4",
        card: "#1f1d2e",
        "card-foreground": "#e0def4",
        popover: "#1f1d2e",
        "popover-foreground": "#e0def4",
        primary: "#ebbcba",
        "primary-foreground": "#191724",
        secondary: "#26233a",
        "secondary-foreground": "#e0def4",
        muted: "#26233a",
        "muted-foreground": "#908caa",
        accent: "#403d52",
        "accent-foreground": "#e0def4",
        destructive: "#eb6f92",
        "destructive-foreground": "#191724",
        border: "#403d52",
        input: "#403d52",
        ring: "#ebbcba",
        "chart-1": "#ebbcba",
        "chart-2": "#f6c177",
        "chart-3": "#9ccfd8",
        "chart-4": "#c4a7e7",
        "chart-5": "#31748f",
        sidebar: "#1f1d2e",
        "sidebar-foreground": "#e0def4",
        "sidebar-primary": "#ebbcba",
        "sidebar-primary-foreground": "#191724",
        "sidebar-accent": "#26233a",
        "sidebar-accent-foreground": "#e0def4",
        "sidebar-border": "#403d52",
        "sidebar-ring": "#ebbcba",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Ocean Breeze — refreshing teal & cyan palette
  // ──────────────────────────────────────────────────────────────────────────
  "ocean-breeze": {
    label: "Ocean Breeze",
    styles: {
      light: {
        background: "#f0fdfa",
        foreground: "#134e4a",
        card: "#ffffff",
        "card-foreground": "#134e4a",
        popover: "#ffffff",
        "popover-foreground": "#134e4a",
        primary: "#0d9488",
        "primary-foreground": "#ffffff",
        secondary: "#ccfbf1",
        "secondary-foreground": "#115e59",
        muted: "#e6fffa",
        "muted-foreground": "#5eead4",
        accent: "#99f6e4",
        "accent-foreground": "#0f766e",
        destructive: "#e11d48",
        "destructive-foreground": "#ffffff",
        border: "#b2f5ea",
        input: "#b2f5ea",
        ring: "#0d9488",
        "chart-1": "#0d9488",
        "chart-2": "#0891b2",
        "chart-3": "#0e7490",
        "chart-4": "#155e75",
        "chart-5": "#164e63",
        radius: "0.75rem",
        sidebar: "#e6fffa",
        "sidebar-foreground": "#134e4a",
        "sidebar-primary": "#0d9488",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#99f6e4",
        "sidebar-accent-foreground": "#0f766e",
        "sidebar-border": "#b2f5ea",
        "sidebar-ring": "#0d9488",
        "font-sans": "DM Sans, sans-serif",
        "font-serif": "Merriweather, serif",
        "font-mono": "Fira Code, monospace",
        "shadow-opacity": "0.08",
        "shadow-blur": "12px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#042f2e",
        foreground: "#ccfbf1",
        card: "#0c4a45",
        "card-foreground": "#ccfbf1",
        popover: "#0c4a45",
        "popover-foreground": "#ccfbf1",
        primary: "#2dd4bf",
        "primary-foreground": "#042f2e",
        secondary: "#115e59",
        "secondary-foreground": "#ccfbf1",
        muted: "#134e4a",
        "muted-foreground": "#5eead4",
        accent: "#0f766e",
        "accent-foreground": "#ccfbf1",
        destructive: "#fb7185",
        "destructive-foreground": "#042f2e",
        border: "#115e59",
        input: "#115e59",
        ring: "#2dd4bf",
        "chart-1": "#2dd4bf",
        "chart-2": "#22d3ee",
        "chart-3": "#06b6d4",
        "chart-4": "#0891b2",
        "chart-5": "#0e7490",
        sidebar: "#0c3b38",
        "sidebar-foreground": "#ccfbf1",
        "sidebar-primary": "#2dd4bf",
        "sidebar-primary-foreground": "#042f2e",
        "sidebar-accent": "#115e59",
        "sidebar-accent-foreground": "#ccfbf1",
        "sidebar-border": "#134e4a",
        "sidebar-ring": "#2dd4bf",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Sunset Ember — warm amber and orange gradients
  // ──────────────────────────────────────────────────────────────────────────
  "sunset-ember": {
    label: "Sunset Ember",
    styles: {
      light: {
        background: "#fffbf5",
        foreground: "#451a03",
        card: "#ffffff",
        "card-foreground": "#451a03",
        popover: "#ffffff",
        "popover-foreground": "#451a03",
        primary: "#ea580c",
        "primary-foreground": "#ffffff",
        secondary: "#fed7aa",
        "secondary-foreground": "#9a3412",
        muted: "#fff7ed",
        "muted-foreground": "#c2410c",
        accent: "#ffedd5",
        "accent-foreground": "#9a3412",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#fed7aa",
        input: "#fed7aa",
        ring: "#ea580c",
        "chart-1": "#ea580c",
        "chart-2": "#f59e0b",
        "chart-3": "#dc2626",
        "chart-4": "#d97706",
        "chart-5": "#92400e",
        radius: "0.625rem",
        sidebar: "#fff7ed",
        "sidebar-foreground": "#451a03",
        "sidebar-primary": "#ea580c",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#ffedd5",
        "sidebar-accent-foreground": "#9a3412",
        "sidebar-border": "#fed7aa",
        "sidebar-ring": "#ea580c",
        "font-sans": "Outfit, sans-serif",
        "font-serif": "Playfair Display, serif",
        "font-mono": "Source Code Pro, monospace",
        "shadow-color": "hsl(24 80% 40%)",
        "shadow-opacity": "0.1",
        "shadow-blur": "6px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "3px",
        "letter-spacing": "-0.01em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#1c0f05",
        foreground: "#fed7aa",
        card: "#2d1a0a",
        "card-foreground": "#fed7aa",
        popover: "#2d1a0a",
        "popover-foreground": "#fed7aa",
        primary: "#fb923c",
        "primary-foreground": "#1c0f05",
        secondary: "#431407",
        "secondary-foreground": "#fed7aa",
        muted: "#3b1106",
        "muted-foreground": "#fdba74",
        accent: "#5c1d09",
        "accent-foreground": "#fed7aa",
        destructive: "#f87171",
        "destructive-foreground": "#1c0f05",
        border: "#5c1d09",
        input: "#5c1d09",
        ring: "#fb923c",
        "chart-1": "#fb923c",
        "chart-2": "#fbbf24",
        "chart-3": "#f87171",
        "chart-4": "#fbbf24",
        "chart-5": "#f59e0b",
        sidebar: "#251108",
        "sidebar-foreground": "#fed7aa",
        "sidebar-primary": "#fb923c",
        "sidebar-primary-foreground": "#1c0f05",
        "sidebar-accent": "#431407",
        "sidebar-accent-foreground": "#fed7aa",
        "sidebar-border": "#5c1d09",
        "sidebar-ring": "#fb923c",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Emerald Noir — deep greens on dark slate
  // ──────────────────────────────────────────────────────────────────────────
  "emerald-noir": {
    label: "Emerald Noir",
    styles: {
      light: {
        background: "#f8fdf8",
        foreground: "#1a2e1a",
        card: "#ffffff",
        "card-foreground": "#1a2e1a",
        popover: "#ffffff",
        "popover-foreground": "#1a2e1a",
        primary: "#059669",
        "primary-foreground": "#ffffff",
        secondary: "#d1fae5",
        "secondary-foreground": "#065f46",
        muted: "#ecfdf5",
        "muted-foreground": "#6b7280",
        accent: "#a7f3d0",
        "accent-foreground": "#064e3b",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#c6f6d5",
        input: "#c6f6d5",
        ring: "#059669",
        "chart-1": "#059669",
        "chart-2": "#10b981",
        "chart-3": "#34d399",
        "chart-4": "#047857",
        "chart-5": "#065f46",
        radius: "0.5rem",
        sidebar: "#ecfdf5",
        "sidebar-foreground": "#1a2e1a",
        "sidebar-primary": "#059669",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d1fae5",
        "sidebar-accent-foreground": "#065f46",
        "sidebar-border": "#c6f6d5",
        "sidebar-ring": "#059669",
        "font-sans": "Geist, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "Geist Mono, monospace",
        "shadow-opacity": "0.06",
        "shadow-blur": "10px",
        "letter-spacing": "-0.015em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#0a1a10",
        foreground: "#d1fae5",
        card: "#0f2a18",
        "card-foreground": "#d1fae5",
        popover: "#0f2a18",
        "popover-foreground": "#d1fae5",
        primary: "#34d399",
        "primary-foreground": "#0a1a10",
        secondary: "#064e3b",
        "secondary-foreground": "#d1fae5",
        muted: "#065f46",
        "muted-foreground": "#6ee7b7",
        accent: "#047857",
        "accent-foreground": "#d1fae5",
        destructive: "#f87171",
        "destructive-foreground": "#0a1a10",
        border: "#064e3b",
        input: "#064e3b",
        ring: "#34d399",
        "chart-1": "#34d399",
        "chart-2": "#6ee7b7",
        "chart-3": "#10b981",
        "chart-4": "#059669",
        "chart-5": "#047857",
        sidebar: "#0c2214",
        "sidebar-foreground": "#d1fae5",
        "sidebar-primary": "#34d399",
        "sidebar-primary-foreground": "#0a1a10",
        "sidebar-accent": "#064e3b",
        "sidebar-accent-foreground": "#d1fae5",
        "sidebar-border": "#065f46",
        "sidebar-ring": "#34d399",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Catppuccin Mocha — beloved pastel community theme
  // ──────────────────────────────────────────────────────────────────────────
  "catppuccin-mocha": {
    label: "Catppuccin Mocha",
    styles: {
      light: {
        background: "#eff1f5",
        foreground: "#4c4f69",
        card: "#e6e9ef",
        "card-foreground": "#4c4f69",
        popover: "#e6e9ef",
        "popover-foreground": "#4c4f69",
        primary: "#8839ef",
        "primary-foreground": "#eff1f5",
        secondary: "#dce0e8",
        "secondary-foreground": "#4c4f69",
        muted: "#dce0e8",
        "muted-foreground": "#7c7f93",
        accent: "#ccd0da",
        "accent-foreground": "#4c4f69",
        destructive: "#d20f39",
        "destructive-foreground": "#eff1f5",
        border: "#ccd0da",
        input: "#ccd0da",
        ring: "#8839ef",
        "chart-1": "#8839ef",
        "chart-2": "#1e66f5",
        "chart-3": "#40a02b",
        "chart-4": "#fe640b",
        "chart-5": "#ea76cb",
        radius: "0.75rem",
        sidebar: "#e6e9ef",
        "sidebar-foreground": "#4c4f69",
        "sidebar-primary": "#8839ef",
        "sidebar-primary-foreground": "#eff1f5",
        "sidebar-accent": "#ccd0da",
        "sidebar-accent-foreground": "#4c4f69",
        "sidebar-border": "#ccd0da",
        "sidebar-ring": "#8839ef",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Crimson Pro, serif",
        "font-mono": "JetBrains Mono, monospace",
        "shadow-opacity": "0.08",
        "shadow-blur": "6px",
        "letter-spacing": "-0.01em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#1e1e2e",
        foreground: "#cdd6f4",
        card: "#313244",
        "card-foreground": "#cdd6f4",
        popover: "#313244",
        "popover-foreground": "#cdd6f4",
        primary: "#cba6f7",
        "primary-foreground": "#1e1e2e",
        secondary: "#45475a",
        "secondary-foreground": "#cdd6f4",
        muted: "#45475a",
        "muted-foreground": "#a6adc8",
        accent: "#585b70",
        "accent-foreground": "#cdd6f4",
        destructive: "#f38ba8",
        "destructive-foreground": "#1e1e2e",
        border: "#45475a",
        input: "#45475a",
        ring: "#cba6f7",
        "chart-1": "#cba6f7",
        "chart-2": "#89b4fa",
        "chart-3": "#a6e3a1",
        "chart-4": "#fab387",
        "chart-5": "#f5c2e7",
        sidebar: "#181825",
        "sidebar-foreground": "#cdd6f4",
        "sidebar-primary": "#cba6f7",
        "sidebar-primary-foreground": "#1e1e2e",
        "sidebar-accent": "#313244",
        "sidebar-accent-foreground": "#cdd6f4",
        "sidebar-border": "#45475a",
        "sidebar-ring": "#cba6f7",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Midnight Sapphire — deep indigo luxury
  // ──────────────────────────────────────────────────────────────────────────
  "midnight-sapphire": {
    label: "Midnight Sapphire",
    styles: {
      light: {
        background: "#f5f7ff",
        foreground: "#1e1b4b",
        card: "#ffffff",
        "card-foreground": "#1e1b4b",
        popover: "#ffffff",
        "popover-foreground": "#1e1b4b",
        primary: "#4338ca",
        "primary-foreground": "#ffffff",
        secondary: "#e0e7ff",
        "secondary-foreground": "#3730a3",
        muted: "#eef2ff",
        "muted-foreground": "#6366f1",
        accent: "#c7d2fe",
        "accent-foreground": "#312e81",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#c7d2fe",
        input: "#c7d2fe",
        ring: "#4338ca",
        "chart-1": "#4338ca",
        "chart-2": "#6366f1",
        "chart-3": "#818cf8",
        "chart-4": "#a5b4fc",
        "chart-5": "#312e81",
        radius: "0.75rem",
        sidebar: "#eef2ff",
        "sidebar-foreground": "#1e1b4b",
        "sidebar-primary": "#4338ca",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e0e7ff",
        "sidebar-accent-foreground": "#3730a3",
        "sidebar-border": "#c7d2fe",
        "sidebar-ring": "#4338ca",
        "font-sans": "Satoshi, sans-serif",
        "font-serif": "Newsreader, serif",
        "font-mono": "Berkeley Mono, monospace",
        "shadow-color": "hsl(238 50% 30%)",
        "shadow-opacity": "0.08",
        "shadow-blur": "16px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
        "letter-spacing": "-0.02em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#0c0a1e",
        foreground: "#e0e7ff",
        card: "#1a1744",
        "card-foreground": "#e0e7ff",
        popover: "#1a1744",
        "popover-foreground": "#e0e7ff",
        primary: "#818cf8",
        "primary-foreground": "#0c0a1e",
        secondary: "#312e81",
        "secondary-foreground": "#e0e7ff",
        muted: "#1e1b4b",
        "muted-foreground": "#a5b4fc",
        accent: "#3730a3",
        "accent-foreground": "#e0e7ff",
        destructive: "#f87171",
        "destructive-foreground": "#0c0a1e",
        border: "#312e81",
        input: "#312e81",
        ring: "#818cf8",
        "chart-1": "#818cf8",
        "chart-2": "#a5b4fc",
        "chart-3": "#6366f1",
        "chart-4": "#4338ca",
        "chart-5": "#c7d2fe",
        sidebar: "#0f0c2a",
        "sidebar-foreground": "#e0e7ff",
        "sidebar-primary": "#818cf8",
        "sidebar-primary-foreground": "#0c0a1e",
        "sidebar-accent": "#1e1b4b",
        "sidebar-accent-foreground": "#e0e7ff",
        "sidebar-border": "#312e81",
        "sidebar-ring": "#818cf8",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Sakura — soft cherry-blossom pink Japanese aesthetic
  // ──────────────────────────────────────────────────────────────────────────
  sakura: {
    label: "Sakura",
    styles: {
      light: {
        background: "#fdf2f8",
        foreground: "#500724",
        card: "#ffffff",
        "card-foreground": "#500724",
        popover: "#ffffff",
        "popover-foreground": "#500724",
        primary: "#db2777",
        "primary-foreground": "#ffffff",
        secondary: "#fce7f3",
        "secondary-foreground": "#9d174d",
        muted: "#fce7f3",
        "muted-foreground": "#be185d",
        accent: "#fbcfe8",
        "accent-foreground": "#831843",
        destructive: "#e11d48",
        "destructive-foreground": "#ffffff",
        border: "#f9a8d4",
        input: "#f9a8d4",
        ring: "#db2777",
        "chart-1": "#db2777",
        "chart-2": "#e879a8",
        "chart-3": "#f472b6",
        "chart-4": "#be185d",
        "chart-5": "#9d174d",
        radius: "1rem",
        sidebar: "#fce7f3",
        "sidebar-foreground": "#500724",
        "sidebar-primary": "#db2777",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fbcfe8",
        "sidebar-accent-foreground": "#831843",
        "sidebar-border": "#f9a8d4",
        "sidebar-ring": "#db2777",
        "font-sans": "Quicksand, sans-serif",
        "font-serif": "Cormorant Garamond, serif",
        "font-mono": "Fira Code, monospace",
        "shadow-color": "hsl(330 60% 60%)",
        "shadow-opacity": "0.1",
        "shadow-blur": "10px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
        "letter-spacing": "0.01em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#1a0510",
        foreground: "#fce7f3",
        card: "#2d0a1c",
        "card-foreground": "#fce7f3",
        popover: "#2d0a1c",
        "popover-foreground": "#fce7f3",
        primary: "#f472b6",
        "primary-foreground": "#1a0510",
        secondary: "#4a0e2e",
        "secondary-foreground": "#fce7f3",
        muted: "#500724",
        "muted-foreground": "#f9a8d4",
        accent: "#831843",
        "accent-foreground": "#fce7f3",
        destructive: "#fb7185",
        "destructive-foreground": "#1a0510",
        border: "#831843",
        input: "#831843",
        ring: "#f472b6",
        "chart-1": "#f472b6",
        "chart-2": "#f9a8d4",
        "chart-3": "#ec4899",
        "chart-4": "#db2777",
        "chart-5": "#fbcfe8",
        sidebar: "#200812",
        "sidebar-foreground": "#fce7f3",
        "sidebar-primary": "#f472b6",
        "sidebar-primary-foreground": "#1a0510",
        "sidebar-accent": "#500724",
        "sidebar-accent-foreground": "#fce7f3",
        "sidebar-border": "#831843",
        "sidebar-ring": "#f472b6",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Nordic Frost — cool slate blues inspired by Scandinavian design
  // ──────────────────────────────────────────────────────────────────────────
  "nordic-frost": {
    label: "Nordic Frost",
    styles: {
      light: {
        background: "#f8fafc",
        foreground: "#0f172a",
        card: "#ffffff",
        "card-foreground": "#0f172a",
        popover: "#ffffff",
        "popover-foreground": "#0f172a",
        primary: "#475569",
        "primary-foreground": "#f8fafc",
        secondary: "#e2e8f0",
        "secondary-foreground": "#334155",
        muted: "#f1f5f9",
        "muted-foreground": "#64748b",
        accent: "#cbd5e1",
        "accent-foreground": "#1e293b",
        destructive: "#ef4444",
        "destructive-foreground": "#f8fafc",
        border: "#e2e8f0",
        input: "#e2e8f0",
        ring: "#475569",
        "chart-1": "#475569",
        "chart-2": "#64748b",
        "chart-3": "#94a3b8",
        "chart-4": "#cbd5e1",
        "chart-5": "#334155",
        radius: "0.375rem",
        sidebar: "#f1f5f9",
        "sidebar-foreground": "#0f172a",
        "sidebar-primary": "#475569",
        "sidebar-primary-foreground": "#f8fafc",
        "sidebar-accent": "#e2e8f0",
        "sidebar-accent-foreground": "#334155",
        "sidebar-border": "#e2e8f0",
        "sidebar-ring": "#475569",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Source Serif 4, serif",
        "font-mono": "JetBrains Mono, monospace",
        "shadow-opacity": "0.04",
        "shadow-blur": "12px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#0f172a",
        foreground: "#e2e8f0",
        card: "#1e293b",
        "card-foreground": "#e2e8f0",
        popover: "#1e293b",
        "popover-foreground": "#e2e8f0",
        primary: "#94a3b8",
        "primary-foreground": "#0f172a",
        secondary: "#334155",
        "secondary-foreground": "#e2e8f0",
        muted: "#334155",
        "muted-foreground": "#94a3b8",
        accent: "#475569",
        "accent-foreground": "#e2e8f0",
        destructive: "#f87171",
        "destructive-foreground": "#0f172a",
        border: "#334155",
        input: "#334155",
        ring: "#94a3b8",
        "chart-1": "#94a3b8",
        "chart-2": "#cbd5e1",
        "chart-3": "#64748b",
        "chart-4": "#475569",
        "chart-5": "#e2e8f0",
        sidebar: "#0c1425",
        "sidebar-foreground": "#e2e8f0",
        "sidebar-primary": "#94a3b8",
        "sidebar-primary-foreground": "#0f172a",
        "sidebar-accent": "#1e293b",
        "sidebar-accent-foreground": "#e2e8f0",
        "sidebar-border": "#334155",
        "sidebar-ring": "#94a3b8",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Cyberpunk Neon — electric greens and magentas on pitch black
  // ──────────────────────────────────────────────────────────────────────────
  "cyberpunk-neon": {
    label: "Cyberpunk Neon",
    styles: {
      light: {
        background: "#fafafa",
        foreground: "#18181b",
        card: "#ffffff",
        "card-foreground": "#18181b",
        popover: "#ffffff",
        "popover-foreground": "#18181b",
        primary: "#a855f7",
        "primary-foreground": "#ffffff",
        secondary: "#fae8ff",
        "secondary-foreground": "#701a75",
        muted: "#fdf4ff",
        "muted-foreground": "#86198f",
        accent: "#e879f9",
        "accent-foreground": "#4a044e",
        destructive: "#f43f5e",
        "destructive-foreground": "#ffffff",
        border: "#e9d5ff",
        input: "#e9d5ff",
        ring: "#a855f7",
        "chart-1": "#a855f7",
        "chart-2": "#22d3ee",
        "chart-3": "#4ade80",
        "chart-4": "#f43f5e",
        "chart-5": "#facc15",
        radius: "0.25rem",
        sidebar: "#fdf4ff",
        "sidebar-foreground": "#18181b",
        "sidebar-primary": "#a855f7",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fae8ff",
        "sidebar-accent-foreground": "#701a75",
        "sidebar-border": "#e9d5ff",
        "sidebar-ring": "#a855f7",
        "font-sans": "Space Grotesk, sans-serif",
        "font-serif": "Space Grotesk, sans-serif",
        "font-mono": "Space Mono, monospace",
        "shadow-opacity": "0.12",
        "shadow-blur": "4px",
        "shadow-spread": "0px",
        "shadow-offset-x": "2px",
        "shadow-offset-y": "2px",
        "letter-spacing": "0.02em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#09090b",
        foreground: "#e4e4e7",
        card: "#18181b",
        "card-foreground": "#e4e4e7",
        popover: "#18181b",
        "popover-foreground": "#e4e4e7",
        primary: "#c084fc",
        "primary-foreground": "#09090b",
        secondary: "#27272a",
        "secondary-foreground": "#e4e4e7",
        muted: "#27272a",
        "muted-foreground": "#a1a1aa",
        accent: "#3f3f46",
        "accent-foreground": "#e4e4e7",
        destructive: "#fb7185",
        "destructive-foreground": "#09090b",
        border: "#3f3f46",
        input: "#3f3f46",
        ring: "#c084fc",
        "chart-1": "#c084fc",
        "chart-2": "#22d3ee",
        "chart-3": "#4ade80",
        "chart-4": "#fb7185",
        "chart-5": "#facc15",
        sidebar: "#0a0a0c",
        "sidebar-foreground": "#e4e4e7",
        "sidebar-primary": "#c084fc",
        "sidebar-primary-foreground": "#09090b",
        "sidebar-accent": "#27272a",
        "sidebar-accent-foreground": "#e4e4e7",
        "sidebar-border": "#3f3f46",
        "sidebar-ring": "#c084fc",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Lavender Dream — soft purple pastels, dreamy and gentle
  // ──────────────────────────────────────────────────────────────────────────
  "lavender-dream": {
    label: "Lavender Dream",
    styles: {
      light: {
        background: "#faf5ff",
        foreground: "#3b0764",
        card: "#ffffff",
        "card-foreground": "#3b0764",
        popover: "#ffffff",
        "popover-foreground": "#3b0764",
        primary: "#9333ea",
        "primary-foreground": "#ffffff",
        secondary: "#f3e8ff",
        "secondary-foreground": "#6b21a8",
        muted: "#f5f3ff",
        "muted-foreground": "#7c3aed",
        accent: "#e9d5ff",
        "accent-foreground": "#581c87",
        destructive: "#e11d48",
        "destructive-foreground": "#ffffff",
        border: "#ddd6fe",
        input: "#ddd6fe",
        ring: "#9333ea",
        "chart-1": "#9333ea",
        "chart-2": "#a78bfa",
        "chart-3": "#c4b5fd",
        "chart-4": "#7c3aed",
        "chart-5": "#6d28d9",
        radius: "1rem",
        sidebar: "#f5f3ff",
        "sidebar-foreground": "#3b0764",
        "sidebar-primary": "#9333ea",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#ede9fe",
        "sidebar-accent-foreground": "#6b21a8",
        "sidebar-border": "#ddd6fe",
        "sidebar-ring": "#9333ea",
        "font-sans": "Nunito Sans, sans-serif",
        "font-serif": "Cormorant, serif",
        "font-mono": "Cascadia Code, monospace",
        "shadow-color": "hsl(270 60% 50%)",
        "shadow-opacity": "0.06",
        "shadow-blur": "14px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "3px",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#13071e",
        foreground: "#f3e8ff",
        card: "#1e0a32",
        "card-foreground": "#f3e8ff",
        popover: "#1e0a32",
        "popover-foreground": "#f3e8ff",
        primary: "#a78bfa",
        "primary-foreground": "#13071e",
        secondary: "#3b0764",
        "secondary-foreground": "#f3e8ff",
        muted: "#4c1d95",
        "muted-foreground": "#c4b5fd",
        accent: "#581c87",
        "accent-foreground": "#f3e8ff",
        destructive: "#fb7185",
        "destructive-foreground": "#13071e",
        border: "#4c1d95",
        input: "#4c1d95",
        ring: "#a78bfa",
        "chart-1": "#a78bfa",
        "chart-2": "#c4b5fd",
        "chart-3": "#8b5cf6",
        "chart-4": "#7c3aed",
        "chart-5": "#ddd6fe",
        sidebar: "#170920",
        "sidebar-foreground": "#f3e8ff",
        "sidebar-primary": "#a78bfa",
        "sidebar-primary-foreground": "#13071e",
        "sidebar-accent": "#3b0764",
        "sidebar-accent-foreground": "#f3e8ff",
        "sidebar-border": "#4c1d95",
        "sidebar-ring": "#a78bfa",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Monokai Warm — inspired by the classic code editor theme
  // ──────────────────────────────────────────────────────────────────────────
  "monokai-warm": {
    label: "Monokai Warm",
    styles: {
      light: {
        background: "#fafaf5",
        foreground: "#3e3d32",
        card: "#ffffff",
        "card-foreground": "#3e3d32",
        popover: "#ffffff",
        "popover-foreground": "#3e3d32",
        primary: "#f92672",
        "primary-foreground": "#ffffff",
        secondary: "#f8f8f2",
        "secondary-foreground": "#3e3d32",
        muted: "#f5f5e8",
        "muted-foreground": "#75715e",
        accent: "#e6db74",
        "accent-foreground": "#3e3d32",
        destructive: "#f92672",
        "destructive-foreground": "#ffffff",
        border: "#e0dfcf",
        input: "#e0dfcf",
        ring: "#f92672",
        "chart-1": "#f92672",
        "chart-2": "#a6e22e",
        "chart-3": "#66d9ef",
        "chart-4": "#e6db74",
        "chart-5": "#ae81ff",
        radius: "0.375rem",
        sidebar: "#f5f5e8",
        "sidebar-foreground": "#3e3d32",
        "sidebar-primary": "#f92672",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e6db74",
        "sidebar-accent-foreground": "#3e3d32",
        "sidebar-border": "#e0dfcf",
        "sidebar-ring": "#f92672",
        "font-sans": "IBM Plex Sans, sans-serif",
        "font-serif": "IBM Plex Serif, serif",
        "font-mono": "IBM Plex Mono, monospace",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#272822",
        foreground: "#f8f8f2",
        card: "#3e3d32",
        "card-foreground": "#f8f8f2",
        popover: "#3e3d32",
        "popover-foreground": "#f8f8f2",
        primary: "#f92672",
        "primary-foreground": "#f8f8f2",
        secondary: "#49483e",
        "secondary-foreground": "#f8f8f2",
        muted: "#49483e",
        "muted-foreground": "#75715e",
        accent: "#3e3d32",
        "accent-foreground": "#e6db74",
        destructive: "#f92672",
        "destructive-foreground": "#f8f8f2",
        border: "#49483e",
        input: "#49483e",
        ring: "#f92672",
        "chart-1": "#f92672",
        "chart-2": "#a6e22e",
        "chart-3": "#66d9ef",
        "chart-4": "#e6db74",
        "chart-5": "#ae81ff",
        sidebar: "#1e1f1c",
        "sidebar-foreground": "#f8f8f2",
        "sidebar-primary": "#f92672",
        "sidebar-primary-foreground": "#f8f8f2",
        "sidebar-accent": "#3e3d32",
        "sidebar-accent-foreground": "#a6e22e",
        "sidebar-border": "#49483e",
        "sidebar-ring": "#f92672",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Tokyo Night — inspired by the popular VS Code theme
  // ──────────────────────────────────────────────────────────────────────────
  "tokyo-night": {
    label: "Tokyo Night",
    styles: {
      light: {
        background: "#f0f0f5",
        foreground: "#343b59",
        card: "#ffffff",
        "card-foreground": "#343b59",
        popover: "#ffffff",
        "popover-foreground": "#343b59",
        primary: "#34548a",
        "primary-foreground": "#ffffff",
        secondary: "#e0e4f0",
        "secondary-foreground": "#343b59",
        muted: "#ebedf5",
        "muted-foreground": "#6c7393",
        accent: "#d4d8e8",
        "accent-foreground": "#343b59",
        destructive: "#c0392b",
        "destructive-foreground": "#ffffff",
        border: "#d0d4e4",
        input: "#d0d4e4",
        ring: "#34548a",
        "chart-1": "#34548a",
        "chart-2": "#965027",
        "chart-3": "#166775",
        "chart-4": "#485e30",
        "chart-5": "#5a4a78",
        radius: "0.5rem",
        sidebar: "#ebedf5",
        "sidebar-foreground": "#343b59",
        "sidebar-primary": "#34548a",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d4d8e8",
        "sidebar-accent-foreground": "#343b59",
        "sidebar-border": "#d0d4e4",
        "sidebar-ring": "#34548a",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Merriweather, serif",
        "font-mono": "JetBrains Mono, monospace",
        "shadow-opacity": "0.06",
        "shadow-blur": "10px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
        "letter-spacing": "-0.01em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#1a1b26",
        foreground: "#a9b1d6",
        card: "#24283b",
        "card-foreground": "#a9b1d6",
        popover: "#24283b",
        "popover-foreground": "#a9b1d6",
        primary: "#7aa2f7",
        "primary-foreground": "#1a1b26",
        secondary: "#292e42",
        "secondary-foreground": "#c0caf5",
        muted: "#292e42",
        "muted-foreground": "#565f89",
        accent: "#33467c",
        "accent-foreground": "#c0caf5",
        destructive: "#f7768e",
        "destructive-foreground": "#1a1b26",
        border: "#3b4261",
        input: "#3b4261",
        ring: "#7aa2f7",
        "chart-1": "#7aa2f7",
        "chart-2": "#ff9e64",
        "chart-3": "#2ac3de",
        "chart-4": "#9ece6a",
        "chart-5": "#bb9af7",
        sidebar: "#16161e",
        "sidebar-foreground": "#a9b1d6",
        "sidebar-primary": "#7aa2f7",
        "sidebar-primary-foreground": "#1a1b26",
        "sidebar-accent": "#292e42",
        "sidebar-accent-foreground": "#c0caf5",
        "sidebar-border": "#3b4261",
        "sidebar-ring": "#7aa2f7",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Solarized — the timeless Ethan Schoonover palette
  // ──────────────────────────────────────────────────────────────────────────
  solarized: {
    label: "Solarized",
    styles: {
      light: {
        background: "#fdf6e3",
        foreground: "#657b83",
        card: "#eee8d5",
        "card-foreground": "#586e75",
        popover: "#eee8d5",
        "popover-foreground": "#586e75",
        primary: "#268bd2",
        "primary-foreground": "#fdf6e3",
        secondary: "#eee8d5",
        "secondary-foreground": "#657b83",
        muted: "#eee8d5",
        "muted-foreground": "#93a1a1",
        accent: "#d6cdb7",
        "accent-foreground": "#586e75",
        destructive: "#dc322f",
        "destructive-foreground": "#fdf6e3",
        border: "#d6cdb7",
        input: "#d6cdb7",
        ring: "#268bd2",
        "chart-1": "#268bd2",
        "chart-2": "#2aa198",
        "chart-3": "#859900",
        "chart-4": "#b58900",
        "chart-5": "#6c71c4",
        radius: "0.5rem",
        sidebar: "#eee8d5",
        "sidebar-foreground": "#586e75",
        "sidebar-primary": "#268bd2",
        "sidebar-primary-foreground": "#fdf6e3",
        "sidebar-accent": "#d6cdb7",
        "sidebar-accent-foreground": "#586e75",
        "sidebar-border": "#d6cdb7",
        "sidebar-ring": "#268bd2",
        "font-sans": "Source Sans 3, sans-serif",
        "font-serif": "Source Serif 4, serif",
        "font-mono": "Source Code Pro, monospace",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#002b36",
        foreground: "#839496",
        card: "#073642",
        "card-foreground": "#93a1a1",
        popover: "#073642",
        "popover-foreground": "#93a1a1",
        primary: "#268bd2",
        "primary-foreground": "#fdf6e3",
        secondary: "#073642",
        "secondary-foreground": "#839496",
        muted: "#073642",
        "muted-foreground": "#586e75",
        accent: "#0a4a5c",
        "accent-foreground": "#93a1a1",
        destructive: "#dc322f",
        "destructive-foreground": "#fdf6e3",
        border: "#0a4a5c",
        input: "#0a4a5c",
        ring: "#268bd2",
        "chart-1": "#268bd2",
        "chart-2": "#2aa198",
        "chart-3": "#859900",
        "chart-4": "#b58900",
        "chart-5": "#6c71c4",
        sidebar: "#001e28",
        "sidebar-foreground": "#839496",
        "sidebar-primary": "#268bd2",
        "sidebar-primary-foreground": "#fdf6e3",
        "sidebar-accent": "#073642",
        "sidebar-accent-foreground": "#93a1a1",
        "sidebar-border": "#0a4a5c",
        "sidebar-ring": "#268bd2",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Dracula — the popular dark theme with vibrant accents
  // ──────────────────────────────────────────────────────────────────────────
  dracula: {
    label: "Dracula",
    styles: {
      light: {
        background: "#f8f8f2",
        foreground: "#282a36",
        card: "#ffffff",
        "card-foreground": "#282a36",
        popover: "#ffffff",
        "popover-foreground": "#282a36",
        primary: "#bd93f9",
        "primary-foreground": "#282a36",
        secondary: "#f0edf7",
        "secondary-foreground": "#282a36",
        muted: "#f4f2fa",
        "muted-foreground": "#6272a4",
        accent: "#e8e0f5",
        "accent-foreground": "#282a36",
        destructive: "#ff5555",
        "destructive-foreground": "#ffffff",
        border: "#e0dae9",
        input: "#e0dae9",
        ring: "#bd93f9",
        "chart-1": "#bd93f9",
        "chart-2": "#50fa7b",
        "chart-3": "#8be9fd",
        "chart-4": "#ffb86c",
        "chart-5": "#ff79c6",
        radius: "0.625rem",
        sidebar: "#f4f2fa",
        "sidebar-foreground": "#282a36",
        "sidebar-primary": "#bd93f9",
        "sidebar-primary-foreground": "#282a36",
        "sidebar-accent": "#e8e0f5",
        "sidebar-accent-foreground": "#282a36",
        "sidebar-border": "#e0dae9",
        "sidebar-ring": "#bd93f9",
        "font-sans": "Rubik, sans-serif",
        "font-serif": "Newsreader, serif",
        "font-mono": "Fira Code, monospace",
        "shadow-opacity": "0.08",
        "shadow-blur": "8px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "3px",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#282a36",
        foreground: "#f8f8f2",
        card: "#44475a",
        "card-foreground": "#f8f8f2",
        popover: "#44475a",
        "popover-foreground": "#f8f8f2",
        primary: "#bd93f9",
        "primary-foreground": "#282a36",
        secondary: "#44475a",
        "secondary-foreground": "#f8f8f2",
        muted: "#44475a",
        "muted-foreground": "#6272a4",
        accent: "#6272a4",
        "accent-foreground": "#f8f8f2",
        destructive: "#ff5555",
        "destructive-foreground": "#f8f8f2",
        border: "#6272a4",
        input: "#6272a4",
        ring: "#bd93f9",
        "chart-1": "#bd93f9",
        "chart-2": "#50fa7b",
        "chart-3": "#8be9fd",
        "chart-4": "#ffb86c",
        "chart-5": "#ff79c6",
        sidebar: "#21222c",
        "sidebar-foreground": "#f8f8f2",
        "sidebar-primary": "#bd93f9",
        "sidebar-primary-foreground": "#282a36",
        "sidebar-accent": "#44475a",
        "sidebar-accent-foreground": "#f8f8f2",
        "sidebar-border": "#6272a4",
        "sidebar-ring": "#bd93f9",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Terracotta — warm earthy browns and clay tones
  // ──────────────────────────────────────────────────────────────────────────
  terracotta: {
    label: "Terracotta",
    styles: {
      light: {
        background: "#faf7f5",
        foreground: "#3c2415",
        card: "#ffffff",
        "card-foreground": "#3c2415",
        popover: "#ffffff",
        "popover-foreground": "#3c2415",
        primary: "#c26a42",
        "primary-foreground": "#ffffff",
        secondary: "#f0e6de",
        "secondary-foreground": "#6b3a22",
        muted: "#f5ede7",
        "muted-foreground": "#8a6b55",
        accent: "#e8d5c4",
        "accent-foreground": "#4a2816",
        destructive: "#c0392b",
        "destructive-foreground": "#ffffff",
        border: "#e0d0c0",
        input: "#e0d0c0",
        ring: "#c26a42",
        "chart-1": "#c26a42",
        "chart-2": "#d4956a",
        "chart-3": "#8b6e55",
        "chart-4": "#a0522d",
        "chart-5": "#6b3a22",
        radius: "0.75rem",
        sidebar: "#f5ede7",
        "sidebar-foreground": "#3c2415",
        "sidebar-primary": "#c26a42",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e8d5c4",
        "sidebar-accent-foreground": "#4a2816",
        "sidebar-border": "#e0d0c0",
        "sidebar-ring": "#c26a42",
        "font-sans": "DM Sans, sans-serif",
        "font-serif": "Playfair Display, serif",
        "font-mono": "Source Code Pro, monospace",
        "shadow-color": "hsl(20 40% 30%)",
        "shadow-opacity": "0.08",
        "shadow-blur": "10px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "3px",
        "letter-spacing": "-0.01em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#1a120d",
        foreground: "#e8d5c4",
        card: "#2a1c14",
        "card-foreground": "#e8d5c4",
        popover: "#2a1c14",
        "popover-foreground": "#e8d5c4",
        primary: "#d4956a",
        "primary-foreground": "#1a120d",
        secondary: "#3c2415",
        "secondary-foreground": "#e8d5c4",
        muted: "#4a2816",
        "muted-foreground": "#b8956e",
        accent: "#5a3520",
        "accent-foreground": "#e8d5c4",
        destructive: "#e74c3c",
        "destructive-foreground": "#1a120d",
        border: "#4a2816",
        input: "#4a2816",
        ring: "#d4956a",
        "chart-1": "#d4956a",
        "chart-2": "#e8b88a",
        "chart-3": "#a0764e",
        "chart-4": "#c26a42",
        "chart-5": "#8a6b55",
        sidebar: "#150e0a",
        "sidebar-foreground": "#e8d5c4",
        "sidebar-primary": "#d4956a",
        "sidebar-primary-foreground": "#1a120d",
        "sidebar-accent": "#3c2415",
        "sidebar-accent-foreground": "#e8d5c4",
        "sidebar-border": "#4a2816",
        "sidebar-ring": "#d4956a",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Aurora Borealis — greens and teals evoking northern lights
  // ──────────────────────────────────────────────────────────────────────────
  "aurora-borealis": {
    label: "Aurora Borealis",
    styles: {
      light: {
        background: "#f2faf8",
        foreground: "#0d3331",
        card: "#ffffff",
        "card-foreground": "#0d3331",
        popover: "#ffffff",
        "popover-foreground": "#0d3331",
        primary: "#0ea5a0",
        "primary-foreground": "#ffffff",
        secondary: "#d4f5ec",
        "secondary-foreground": "#0d3331",
        muted: "#e8f8f4",
        "muted-foreground": "#4e8a78",
        accent: "#81e6d9",
        "accent-foreground": "#0d3331",
        destructive: "#e53e3e",
        "destructive-foreground": "#ffffff",
        border: "#b8ede2",
        input: "#b8ede2",
        ring: "#0ea5a0",
        "chart-1": "#0ea5a0",
        "chart-2": "#38b2ac",
        "chart-3": "#4fd1c5",
        "chart-4": "#81e6d9",
        "chart-5": "#06716d",
        radius: "0.75rem",
        sidebar: "#e8f8f4",
        "sidebar-foreground": "#0d3331",
        "sidebar-primary": "#0ea5a0",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d4f5ec",
        "sidebar-accent-foreground": "#0d3331",
        "sidebar-border": "#b8ede2",
        "sidebar-ring": "#0ea5a0",
        "font-sans": "Figtree, sans-serif",
        "font-serif": "Libre Baskerville, serif",
        "font-mono": "Cascadia Code, monospace",
        "shadow-color": "hsl(174 60% 30%)",
        "shadow-opacity": "0.06",
        "shadow-blur": "12px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "3px",
        "letter-spacing": "-0.01em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#0a1e1c",
        foreground: "#b8ede2",
        card: "#122e2b",
        "card-foreground": "#b8ede2",
        popover: "#122e2b",
        "popover-foreground": "#b8ede2",
        primary: "#4fd1c5",
        "primary-foreground": "#0a1e1c",
        secondary: "#164e48",
        "secondary-foreground": "#b8ede2",
        muted: "#1a3c38",
        "muted-foreground": "#6cc9bc",
        accent: "#0d5c55",
        "accent-foreground": "#b8ede2",
        destructive: "#fc8181",
        "destructive-foreground": "#0a1e1c",
        border: "#1a3c38",
        input: "#1a3c38",
        ring: "#4fd1c5",
        "chart-1": "#4fd1c5",
        "chart-2": "#81e6d9",
        "chart-3": "#38b2ac",
        "chart-4": "#0ea5a0",
        "chart-5": "#b8ede2",
        sidebar: "#071917",
        "sidebar-foreground": "#b8ede2",
        "sidebar-primary": "#4fd1c5",
        "sidebar-primary-foreground": "#0a1e1c",
        "sidebar-accent": "#164e48",
        "sidebar-accent-foreground": "#b8ede2",
        "sidebar-border": "#1a3c38",
        "sidebar-ring": "#4fd1c5",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Crimson Royale — rich reds and golds for a regal feel
  // ──────────────────────────────────────────────────────────────────────────
  "crimson-royale": {
    label: "Crimson Royale",
    styles: {
      light: {
        background: "#fdf8f6",
        foreground: "#3b1018",
        card: "#ffffff",
        "card-foreground": "#3b1018",
        popover: "#ffffff",
        "popover-foreground": "#3b1018",
        primary: "#be123c",
        "primary-foreground": "#ffffff",
        secondary: "#fce4ec",
        "secondary-foreground": "#7f1d2f",
        muted: "#fdf2f4",
        "muted-foreground": "#a0616c",
        accent: "#f9d0d8",
        "accent-foreground": "#5c1525",
        destructive: "#991b1b",
        "destructive-foreground": "#ffffff",
        border: "#f0c0c8",
        input: "#f0c0c8",
        ring: "#be123c",
        "chart-1": "#be123c",
        "chart-2": "#e11d48",
        "chart-3": "#f43f5e",
        "chart-4": "#d4a017",
        "chart-5": "#7f1d2f",
        radius: "0.5rem",
        sidebar: "#fdf2f4",
        "sidebar-foreground": "#3b1018",
        "sidebar-primary": "#be123c",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fce4ec",
        "sidebar-accent-foreground": "#7f1d2f",
        "sidebar-border": "#f0c0c8",
        "sidebar-ring": "#be123c",
        "font-sans": "Lora, serif",
        "font-serif": "Cormorant Garamond, serif",
        "font-mono": "Fira Code, monospace",
        "shadow-color": "hsl(350 60% 30%)",
        "shadow-opacity": "0.08",
        "shadow-blur": "12px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#1a080c",
        foreground: "#fce4ec",
        card: "#2a0e16",
        "card-foreground": "#fce4ec",
        popover: "#2a0e16",
        "popover-foreground": "#fce4ec",
        primary: "#fb7185",
        "primary-foreground": "#1a080c",
        secondary: "#5c1525",
        "secondary-foreground": "#fce4ec",
        muted: "#4a1020",
        "muted-foreground": "#f9a8b8",
        accent: "#7f1d2f",
        "accent-foreground": "#fce4ec",
        destructive: "#f87171",
        "destructive-foreground": "#1a080c",
        border: "#5c1525",
        input: "#5c1525",
        ring: "#fb7185",
        "chart-1": "#fb7185",
        "chart-2": "#f9a8b8",
        "chart-3": "#f43f5e",
        "chart-4": "#fbbf24",
        "chart-5": "#be123c",
        sidebar: "#140610",
        "sidebar-foreground": "#fce4ec",
        "sidebar-primary": "#fb7185",
        "sidebar-primary-foreground": "#1a080c",
        "sidebar-accent": "#4a1020",
        "sidebar-accent-foreground": "#fce4ec",
        "sidebar-border": "#5c1525",
        "sidebar-ring": "#fb7185",
      },
    },
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Gruvbox — retro groovy warm colors
  // ──────────────────────────────────────────────────────────────────────────
  gruvbox: {
    label: "Gruvbox",
    styles: {
      light: {
        background: "#fbf1c7",
        foreground: "#3c3836",
        card: "#f9f5d7",
        "card-foreground": "#3c3836",
        popover: "#f9f5d7",
        "popover-foreground": "#3c3836",
        primary: "#d65d0e",
        "primary-foreground": "#fbf1c7",
        secondary: "#ebdbb2",
        "secondary-foreground": "#3c3836",
        muted: "#ebdbb2",
        "muted-foreground": "#7c6f64",
        accent: "#d5c4a1",
        "accent-foreground": "#3c3836",
        destructive: "#cc241d",
        "destructive-foreground": "#fbf1c7",
        border: "#d5c4a1",
        input: "#d5c4a1",
        ring: "#d65d0e",
        "chart-1": "#d65d0e",
        "chart-2": "#98971a",
        "chart-3": "#458588",
        "chart-4": "#b16286",
        "chart-5": "#689d6a",
        radius: "0.375rem",
        sidebar: "#ebdbb2",
        "sidebar-foreground": "#3c3836",
        "sidebar-primary": "#d65d0e",
        "sidebar-primary-foreground": "#fbf1c7",
        "sidebar-accent": "#d5c4a1",
        "sidebar-accent-foreground": "#3c3836",
        "sidebar-border": "#d5c4a1",
        "sidebar-ring": "#d65d0e",
        "font-sans": "IBM Plex Sans, sans-serif",
        "font-serif": "IBM Plex Serif, serif",
        "font-mono": "IBM Plex Mono, monospace",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#282828",
        foreground: "#ebdbb2",
        card: "#3c3836",
        "card-foreground": "#ebdbb2",
        popover: "#3c3836",
        "popover-foreground": "#ebdbb2",
        primary: "#fe8019",
        "primary-foreground": "#282828",
        secondary: "#504945",
        "secondary-foreground": "#ebdbb2",
        muted: "#504945",
        "muted-foreground": "#a89984",
        accent: "#665c54",
        "accent-foreground": "#ebdbb2",
        destructive: "#fb4934",
        "destructive-foreground": "#282828",
        border: "#504945",
        input: "#504945",
        ring: "#fe8019",
        "chart-1": "#fe8019",
        "chart-2": "#b8bb26",
        "chart-3": "#83a598",
        "chart-4": "#d3869b",
        "chart-5": "#8ec07c",
        sidebar: "#1d2021",
        "sidebar-foreground": "#ebdbb2",
        "sidebar-primary": "#fe8019",
        "sidebar-primary-foreground": "#282828",
        "sidebar-accent": "#3c3836",
        "sidebar-accent-foreground": "#ebdbb2",
        "sidebar-border": "#504945",
        "sidebar-ring": "#fe8019",
      },
    },
  },
  valentineBlush: {
    label: "Valentine Blush",
    styles: {
      light: {
        background: "#fff5f7",
        foreground: "#4a1028",
        card: "#ffffff",
        "card-foreground": "#4a1028",
        popover: "#ffffff",
        "popover-foreground": "#4a1028",
        primary: "#e63972",
        "primary-foreground": "#ffffff",
        secondary: "#fce4ec",
        "secondary-foreground": "#880e4f",
        muted: "#fdf2f4",
        "muted-foreground": "#a0616c",
        accent: "#fce4ec",
        "accent-foreground": "#880e4f",
        destructive: "#c62828",
        "destructive-foreground": "#ffffff",
        border: "#f8bbd0",
        input: "#f8bbd0",
        ring: "#e63972",
        "chart-1": "#e63972",
        "chart-2": "#f06292",
        "chart-3": "#ec407a",
        "chart-4": "#ad1457",
        "chart-5": "#880e4f",
        sidebar: "#fdf2f4",
        "sidebar-foreground": "#4a1028",
        "sidebar-primary": "#e63972",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fce4ec",
        "sidebar-accent-foreground": "#880e4f",
        "sidebar-border": "#f8bbd0",
        "sidebar-ring": "#e63972",
      },
      dark: {
        background: "#1a0510",
        foreground: "#fce4ec",
        card: "#2d0a1c",
        "card-foreground": "#fce4ec",
        popover: "#2d0a1c",
        "popover-foreground": "#fce4ec",
        primary: "#f472b6",
        "primary-foreground": "#1a0510",
        secondary: "#4a0e2e",
        "secondary-foreground": "#fce4ec",
        muted: "#3b0822",
        "muted-foreground": "#f9a8b8",
        accent: "#5c1535",
        "accent-foreground": "#fce4ec",
        destructive: "#fb7185",
        "destructive-foreground": "#1a0510",
        border: "#6b1d3f",
        input: "#6b1d3f",
        ring: "#f472b6",
        "chart-1": "#f472b6",
        "chart-2": "#f9a8d4",
        "chart-3": "#ec4899",
        "chart-4": "#db2777",
        "chart-5": "#fbcfe8",
        sidebar: "#200812",
        "sidebar-foreground": "#fce4ec",
        "sidebar-primary": "#f472b6",
        "sidebar-primary-foreground": "#1a0510",
        "sidebar-accent": "#3b0822",
        "sidebar-accent-foreground": "#fce4ec",
        "sidebar-border": "#5c1535",
        "sidebar-ring": "#f472b6",
      },
    },
  },

  midnightRomance: {
    label: "Midnight Romance",

    styles: {
      light: {
        background: "#fdf2f8",
        foreground: "#3b0764",
        card: "#ffffff",
        "card-foreground": "#3b0764",
        popover: "#ffffff",
        "popover-foreground": "#3b0764",
        primary: "#a21caf",
        "primary-foreground": "#ffffff",
        secondary: "#f5d0fe",
        "secondary-foreground": "#6b21a8",
        muted: "#fae8ff",
        "muted-foreground": "#86198f",
        accent: "#f5d0fe",
        "accent-foreground": "#6b21a8",
        destructive: "#be123c",
        "destructive-foreground": "#ffffff",
        border: "#e9d5ff",
        input: "#e9d5ff",
        ring: "#a21caf",
        "chart-1": "#a21caf",
        "chart-2": "#c026d3",
        "chart-3": "#d946ef",
        "chart-4": "#7c3aed",
        "chart-5": "#6d28d9",
        sidebar: "#faf5ff",
        "sidebar-foreground": "#3b0764",
        "sidebar-primary": "#a21caf",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f5d0fe",
        "sidebar-accent-foreground": "#6b21a8",
        "sidebar-border": "#e9d5ff",
        "sidebar-ring": "#a21caf",
      },
      dark: {
        background: "#150520",
        foreground: "#fae8ff",
        card: "#240936",
        "card-foreground": "#fae8ff",
        popover: "#240936",
        "popover-foreground": "#fae8ff",
        primary: "#d946ef",
        "primary-foreground": "#150520",
        secondary: "#4c1d95",
        "secondary-foreground": "#fae8ff",
        muted: "#3b0764",
        "muted-foreground": "#d8b4fe",
        accent: "#581c87",
        "accent-foreground": "#fae8ff",
        destructive: "#fb7185",
        "destructive-foreground": "#150520",
        border: "#6b21a8",
        input: "#6b21a8",
        ring: "#d946ef",
        "chart-1": "#d946ef",
        "chart-2": "#a855f7",
        "chart-3": "#c084fc",
        "chart-4": "#e879f9",
        "chart-5": "#f0abfc",
        sidebar: "#1c0730",
        "sidebar-foreground": "#fae8ff",
        "sidebar-primary": "#d946ef",
        "sidebar-primary-foreground": "#150520",
        "sidebar-accent": "#3b0764",
        "sidebar-accent-foreground": "#fae8ff",
        "sidebar-border": "#581c87",
        "sidebar-ring": "#d946ef",
      },
    },
  },

  cupidsArrow: {
    label: "Cupid's Arrow",
    styles: {
      light: {
        background: "#fff8f0",
        foreground: "#5c1a0a",
        card: "#ffffff",
        "card-foreground": "#5c1a0a",
        popover: "#ffffff",
        "popover-foreground": "#5c1a0a",
        primary: "#dc2626",
        "primary-foreground": "#ffffff",
        secondary: "#fef3c7",
        "secondary-foreground": "#92400e",
        muted: "#fef9ee",
        "muted-foreground": "#a16207",
        accent: "#fde68a",
        "accent-foreground": "#78350f",
        destructive: "#b91c1c",
        "destructive-foreground": "#ffffff",
        border: "#fcd34d",
        input: "#fcd34d",
        ring: "#dc2626",
        "chart-1": "#dc2626",
        "chart-2": "#f59e0b",
        "chart-3": "#ef4444",
        "chart-4": "#d97706",
        "chart-5": "#b91c1c",
        sidebar: "#fef9ee",
        "sidebar-foreground": "#5c1a0a",
        "sidebar-primary": "#dc2626",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fef3c7",
        "sidebar-accent-foreground": "#92400e",
        "sidebar-border": "#fcd34d",
        "sidebar-ring": "#dc2626",
      },
      dark: {
        background: "#1c0808",
        foreground: "#fef2f2",
        card: "#2a0e0e",
        "card-foreground": "#fef2f2",
        popover: "#2a0e0e",
        "popover-foreground": "#fef2f2",
        primary: "#f87171",
        "primary-foreground": "#1c0808",
        secondary: "#451a03",
        "secondary-foreground": "#fef3c7",
        muted: "#3b0f0f",
        "muted-foreground": "#fca5a5",
        accent: "#78350f",
        "accent-foreground": "#fef3c7",
        destructive: "#fca5a5",
        "destructive-foreground": "#1c0808",
        border: "#7c2d12",
        input: "#7c2d12",
        ring: "#f87171",
        "chart-1": "#f87171",
        "chart-2": "#fbbf24",
        "chart-3": "#fb923c",
        "chart-4": "#f59e0b",
        "chart-5": "#fcd34d",
        sidebar: "#220c0c",
        "sidebar-foreground": "#fef2f2",
        "sidebar-primary": "#f87171",
        "sidebar-primary-foreground": "#1c0808",
        "sidebar-accent": "#3b0f0f",
        "sidebar-accent-foreground": "#fef2f2",
        "sidebar-border": "#7f1d1d",
        "sidebar-ring": "#f87171",
      },
    },
  },

  cottonCandyLove: {
    label: "Cotton Candy Love",

    styles: {
      light: {
        background: "#fdf4ff",
        foreground: "#3b1055",
        card: "#ffffff",
        "card-foreground": "#3b1055",
        popover: "#ffffff",
        "popover-foreground": "#3b1055",
        primary: "#ec4899",
        "primary-foreground": "#ffffff",
        secondary: "#dbeafe",
        "secondary-foreground": "#1e40af",
        muted: "#fce7f3",
        "muted-foreground": "#9d4edd",
        accent: "#c7d2fe",
        "accent-foreground": "#3730a3",
        destructive: "#e11d48",
        "destructive-foreground": "#ffffff",
        border: "#f9a8d4",
        input: "#f9a8d4",
        ring: "#ec4899",
        "chart-1": "#ec4899",
        "chart-2": "#818cf8",
        "chart-3": "#f472b6",
        "chart-4": "#a78bfa",
        "chart-5": "#c084fc",
        sidebar: "#fdf4ff",
        "sidebar-foreground": "#3b1055",
        "sidebar-primary": "#ec4899",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#dbeafe",
        "sidebar-accent-foreground": "#1e40af",
        "sidebar-border": "#f9a8d4",
        "sidebar-ring": "#ec4899",
      },
      dark: {
        background: "#0f0720",
        foreground: "#f5d0fe",
        card: "#1a0e30",
        "card-foreground": "#f5d0fe",
        popover: "#1a0e30",
        "popover-foreground": "#f5d0fe",
        primary: "#f9a8d4",
        "primary-foreground": "#0f0720",
        secondary: "#1e1b4b",
        "secondary-foreground": "#c7d2fe",
        muted: "#2e1065",
        "muted-foreground": "#e9d5ff",
        accent: "#312e81",
        "accent-foreground": "#c7d2fe",
        destructive: "#fb7185",
        "destructive-foreground": "#0f0720",
        border: "#4c1d95",
        input: "#4c1d95",
        ring: "#f9a8d4",
        "chart-1": "#f9a8d4",
        "chart-2": "#a5b4fc",
        "chart-3": "#fbcfe8",
        "chart-4": "#c4b5fd",
        "chart-5": "#e9d5ff",
        sidebar: "#130a25",
        "sidebar-foreground": "#f5d0fe",
        "sidebar-primary": "#f9a8d4",
        "sidebar-primary-foreground": "#0f0720",
        "sidebar-accent": "#2e1065",
        "sidebar-accent-foreground": "#f5d0fe",
        "sidebar-border": "#4c1d95",
        "sidebar-ring": "#f9a8d4",
      },
    },
  },
};
